<h1>1D array</h1>

In [6]:
import numpy as np

In [2]:
## creation of array 1D
arr1 = np.array([25,41,63,66,85,74])
arr1

array([25, 41, 63, 66, 85, 74])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr1.size

6

In [5]:
len(arr1)

6

In [6]:
print(np.__version__)

2.0.0


In [7]:
arr1[::]

array([25, 41, 63, 66, 85, 74])

In [9]:
arr1[-1] = 500

In [10]:
arr1

array([ 25,  41,  63,  66,  85, 500])

In [11]:
arr1 + 2

array([ 27,  43,  65,  68,  87, 502])

In [12]:
arr1 * 2

array([  50,   82,  126,  132,  170, 1000])

In [13]:
arr1.dtype

dtype('int64')

<h2>arr1 = np.array([10,20,30,40]) <- 1D 
</br>
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) <- 2D</h2>

<h1>2D array</h1>

In [5]:
import numpy as np

In [6]:
ls = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [7]:
arr2 = np.array(ls)
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
arr2[1]

array([4, 5, 6])

In [9]:
arr = np.random.randint(1,200,500)
arr

array([ 34, 186, 193, 128,   7, 171,  23,  60,  63, 159, 124,  57,  77,
        22, 194,  19,  17,  72, 138, 176,  28,  49,  90,  48, 118,  81,
        98,  23,   4,  86,  41, 114,  57, 192,  30, 108,  63,  16,  71,
        12,  70,  73,  13,  22, 138,  75, 175,  27, 100, 141,  92,  41,
        77, 113, 156, 188,  44,  31,  82,  14,  63, 192, 180, 142, 147,
       107, 164,  62, 121, 133, 167,  92,  92,   2,  11,  18, 154,  66,
       135, 112,  52,  14, 164, 189, 131, 165,  90, 182, 168,  73,  63,
        70, 166, 114, 152, 177,  97, 121, 195, 147,  75,  64,  42, 163,
        17, 191,  84,  24, 133,  75, 160,  34,  70,  70,  57, 164, 197,
        22, 155, 108,  87, 182, 118, 164,  26,  39, 138, 122, 193,  31,
       171,  49, 190,  99,  48, 182, 163, 114,  64, 172, 175, 145, 130,
       122, 195, 178,  27,  78, 176, 107,  44,  55, 198,  48, 183,  29,
       154, 151, 113,   8, 150,  30,  76, 107, 104,  10, 148, 194,  18,
       147, 103,  88, 115,  48, 161, 117,  20,  10,  26,  39,  1

In [10]:
arr[arr <= 100]

array([ 34,   7,  23,  60,  63,  57,  77,  22,  19,  17,  72,  28,  49,
        90,  48,  81,  98,  23,   4,  86,  41,  57,  30,  63,  16,  71,
        12,  70,  73,  13,  22,  75,  27, 100,  92,  41,  77,  44,  31,
        82,  14,  63,  62,  92,  92,   2,  11,  18,  66,  52,  14,  90,
        73,  63,  70,  97,  75,  64,  42,  17,  84,  24,  75,  34,  70,
        70,  57,  22,  87,  26,  39,  31,  49,  99,  48,  64,  27,  78,
        44,  55,  48,  29,   8,  30,  76,  10,  18,  88,  48,  20,  10,
        26,  39,  17,  51,  85,  47,  77,  89,  48,   2,  40,   2,  72,
        89,  41,  38,  32,   2,  21,  81,  38,  28,   6,  74,  65,  60,
        34,  27,  50,  72,  29,  54,  71,  75,  57,  74,  69,  41,  52,
         3,  22,  63,  89,  72,  77,  68,  50,  11,  72,  60,  52,  47,
        20,  54,  11,  94,  25,  71, 100,  87,  38,  84,  62,  99,  23,
        19, 100,   3,  56,  79,   4,  11,  51,  86,  85,  52,  85,  21,
        84,  78,  12,   7,  59,  33,  36,  82,  94,  45,  52,  4

In [11]:
arr[arr <= 100].shape

(245,)

In [12]:
arr2 = np.random.randint(1,200,(10,5))
arr2

array([[ 13, 192, 110,  28,  49],
       [  5,  23,  23, 177,   6],
       [  6, 175, 179, 191, 114],
       [ 46,  63, 113, 199, 117],
       [114,  31,  28,  11,  44],
       [ 36,  33,   1,  40, 155],
       [ 20, 143,  88, 161,  63],
       [ 60,  14,  47,  12, 106],
       [146, 144, 180, 108,  29],
       [ 96,  32,  18, 169, 173]], dtype=int32)

In [13]:
# next day

In [16]:
arr = np.array([8,7,9])
arr

array([8, 7, 9])

In [17]:
np.max(arr)

np.int64(9)

In [18]:
np.min(arr)

np.int64(7)

In [19]:
np.mean(arr)

np.float64(8.0)

In [20]:
np.sum(arr)

np.int64(24)

In [21]:
np.argmin(arr)

np.int64(1)

In [22]:
np.argmax(arr)

np.int64(2)

In [24]:
np.sort(arr)

array([7, 8, 9])

In [25]:
arr[::-1]

array([9, 7, 8])